default_kp: 20.0
default_kd: 1.0

default_joints:
  joints:
    - name: 'left_hip_pitch_joint'
      position: -0.05
      kp: 40
      kd: 4
    - name: 'left_hip_roll_joint'
      position: 0.0
      kp: 40
      kd: 4
    - name: 'left_hip_yaw_joint'
      position: 0.0
      kp: 30
      kd: 3
    - name: 'left_knee_joint'
      position: 0.1
      kp: 80
      kd: 8
    - name: 'left_ankle_pitch_joint'
      position: -0.05
      kp: 40
      kd: 4
    - name: 'left_ankle_roll_joint'
      position: 0.0
      kp: 20
      kd: 2
    - name: 'right_hip_pitch_joint'
      position: -0.05
      kp: 40
      kd: 4
    - name: 'right_hip_roll_joint'
      position: 0.0
      kp: 40
      kd: 4
    - name: 'right_hip_yaw_joint'
      position: 0.0
      kp: 30
      kd: 3
    - name: 'right_knee_joint'
      position: 0.1
      kp: 80
      kd: 8
    - name: 'right_ankle_pitch_joint'
      position: -0.05
      kp: 40
      kd: 4
    - name: 'right_ankle_roll_joint'
      position: 0.0
      kp: 20
      kd: 2
    - name: 'left_shoulder_pitch_joint'
      position: 0.4
      kp: 30
      kd: 1
    - name: 'right_shoulder_pitch_joint'
      position: 0.4
      kp: 30
      kd: 1
    - name: 'left_elbow_joint'
      position: -1.2
      kp: 50
      kd: 1
    - name: 'right_elbow_joint'
      position: -1.2
      kp: 50
      kd: 1
    - name: 'left_wrist_yaw_joint'
      position: 0
      kp: 50
      kd: 1
    - name: 'right_wrist_yaw_joint'
      position: 0
      kp: 50
      kd: 1
    - name: 'waist_yaw_joint'
      position: 0.0
      kp: 150
      kd: 3
    - name: 'waist_pitch_joint'
      position: 0.0
      kp: 300
      kd: 3
    - name: 'waist_roll_joint'
      position: 0.0
      kp: 300
      kd: 3

rl_config:
  policy:
    type: "onnx"
    device: "cpu"
    path: "x2_rl_deploy_controller/config/rl_model/kuailechongbai.onnx"

  infer:
    frame_stack: 5
  dt: 0.02  # 50Hz
  clips:
    obs_clip: 100.0
    action_clip: 100.0
    
  seq:
    [
      'left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint',
      'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_pitch_joint',
      'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_roll_joint',
      'left_knee_joint', 'right_knee_joint', 
      'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint',
      'left_ankle_pitch_joint', 'right_ankle_pitch_joint',
      'left_shoulder_roll_joint', 'right_shoulder_roll_joint',
      'left_ankle_roll_joint', 'right_ankle_roll_joint',
      'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint',
      'left_elbow_joint', 'right_elbow_joint',
      'left_wrist_yaw_joint', 'right_wrist_yaw_joint',
      'left_wrist_pitch_joint', 'right_wrist_pitch_joint', 
      'left_wrist_roll_joint', 'right_wrist_roll_joint'
    ]
  action_seq:
    [
      'left_hip_pitch_joint', 'right_hip_pitch_joint', 'waist_yaw_joint',
      'left_hip_roll_joint', 'right_hip_roll_joint', 'waist_pitch_joint',
      'left_hip_yaw_joint', 'right_hip_yaw_joint', 'waist_roll_joint',
      'left_knee_joint', 'right_knee_joint', 
      'left_shoulder_pitch_joint', 'right_shoulder_pitch_joint',
      'left_ankle_pitch_joint', 'right_ankle_pitch_joint',
      'left_shoulder_roll_joint', 'right_shoulder_roll_joint',
      'left_ankle_roll_joint', 'right_ankle_roll_joint',
      'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint',
      'left_elbow_joint', 'right_elbow_joint',
      'left_wrist_yaw_joint', 'right_wrist_yaw_joint',
      'left_wrist_pitch_joint', 'right_wrist_pitch_joint', 
      'left_wrist_roll_joint', 'right_wrist_roll_joint'
    ]
  default_dof_pos: [  
    -0.3120, -0.3120, 0.0000,
    0.0000,  0.0000, 0.0000,
    0.0000,  0.0000, 0.0000,
    0.6690,  0.6690,
    0.2000,  0.2000,
    -0.3630, -0.3630,
    0.2000, -0.2000,  
    0.0000,  0.0000,  
    0.0000,  0.0000, 
    -0.3000, -0.3000,  
    0.0000,  0.0000, 
    0.0000,  0.0000,
    0.0000,  0.0000,
  ]

  kps: [
    120.0000, 120.0000,  40.1792, 100.0000, 100.0000, 200.0000, 100.0000,
    100.0000, 200.0000, 150.0000, 150.0000,  50.0000,  50.0000,  40.0000,
    40.0000,  50.0000,  50.0000,  40.0000,  40.0000,  50.0000,  50.0000,
    50.0000,  50.0000,  20.0000,  20.0000,  20.0000,  20.0000,  20.0000,
    20.0000
  ]
  kds: [ 
    5.0000, 5.0000, 2.5579, 4.0000, 4.0000, 2.0000, 4.0000, 4.0000, 2.0000,
    5.0000, 5.0000, 3.0000, 3.0000, 2.0000, 2.0000, 3.0000, 3.0000, 2.0000,
    2.0000, 3.0000, 3.0000, 3.0000, 3.0000, 2.0000, 2.0000, 2.0000, 2.0000,
    2.0000, 2.0000 
  ]

  action_scale: 0.25

  num_q: 29
  num_actions: 29
  num_obs: 151

  obs_scales:
    ang_vel: 0.25
    dof_pos: 1.0
    dof_vel: 0.05
    actions: 1.0
    history_actor: 1.0
    lin_vel: 1.0

  phase:
    start_count: 1
    end_count: 2820
