from aimdk_msgs.msg._agent_properties import AgentProperties  # noqa: F401
from aimdk_msgs.msg._agent_properties_value import AgentPropertiesValue  # noqa: F401
from aimdk_msgs.msg._agent_property_id_type import AgentPropertyIdType  # noqa: F401
from aimdk_msgs.msg._audio_capture import AudioCapture  # noqa: F401
from aimdk_msgs.msg._audio_data import AudioData  # noqa: F401
from aimdk_msgs.msg._audio_file import AudioFile  # noqa: F401
from aimdk_msgs.msg._audio_info import AudioInfo  # noqa: F401
from aimdk_msgs.msg._audio_playback import AudioPlayback  # noqa: F401
from aimdk_msgs.msg._audio_vad_state_type import AudioVadStateType  # noqa: F401
from aimdk_msgs.msg._common_request import CommonRequest  # noqa: F401
from aimdk_msgs.msg._common_response import CommonResponse  # noqa: F401
from aimdk_msgs.msg._common_state import CommonState  # noqa: F401
from aimdk_msgs.msg._common_task_response import CommonTaskResponse  # noqa: F401
from aimdk_msgs.msg._current_version import CurrentVersion  # noqa: F401
from aimdk_msgs.msg._domain_error_state import DomainErrorState  # noqa: F401
from aimdk_msgs.msg._face_emoji_status import FaceEmojiStatus  # noqa: F401
from aimdk_msgs.msg._focus_requester import FocusRequester  # noqa: F401
from aimdk_msgs.msg._focus_response import FocusResponse  # noqa: F401
from aimdk_msgs.msg._hand_command import HandCommand  # noqa: F401
from aimdk_msgs.msg._hand_command_array import HandCommandArray  # noqa: F401
from aimdk_msgs.msg._hand_state import HandState  # noqa: F401
from aimdk_msgs.msg._hand_state_array import HandStateArray  # noqa: F401
from aimdk_msgs.msg._hand_touch_sensor_data import HandTouchSensorData  # noqa: F401
from aimdk_msgs.msg._hand_type import HandType  # noqa: F401
from aimdk_msgs.msg._hr_point import HRPoint  # noqa: F401
from aimdk_msgs.msg._joint_command import JointCommand  # noqa: F401
from aimdk_msgs.msg._joint_command_array import JointCommandArray  # noqa: F401
from aimdk_msgs.msg._joint_state import JointState  # noqa: F401
from aimdk_msgs.msg._joint_state_array import JointStateArray  # noqa: F401
from aimdk_msgs.msg._mc_action import McAction  # noqa: F401
from aimdk_msgs.msg._mc_action_command import McActionCommand  # noqa: F401
from aimdk_msgs.msg._mc_action_info import McActionInfo  # noqa: F401
from aimdk_msgs.msg._mc_action_status import McActionStatus  # noqa: F401
from aimdk_msgs.msg._mc_control_area import McControlArea  # noqa: F401
from aimdk_msgs.msg._mc_input_action import McInputAction  # noqa: F401
from aimdk_msgs.msg._mc_input_source import McInputSource  # noqa: F401
from aimdk_msgs.msg._mc_locomotion_velocity import McLocomotionVelocity  # noqa: F401
from aimdk_msgs.msg._mc_preset_motion import McPresetMotion  # noqa: F401
from aimdk_msgs.msg._message_header import MessageHeader  # noqa: F401
from aimdk_msgs.msg._navi_point import NaviPoint  # noqa: F401
from aimdk_msgs.msg._path import Path  # noqa: F401
from aimdk_msgs.msg._play_media_file_request import PlayMediaFileRequest  # noqa: F401
from aimdk_msgs.msg._play_state_change import PlayStateChange  # noqa: F401
from aimdk_msgs.msg._play_state_type import PlayStateType  # noqa: F401
from aimdk_msgs.msg._play_tts_request import PlayTtsRequest  # noqa: F401
from aimdk_msgs.msg._play_tts_response import PlayTtsResponse  # noqa: F401
from aimdk_msgs.msg._pmu_state import PmuState  # noqa: F401
from aimdk_msgs.msg._processed_audio_output import ProcessedAudioOutput  # noqa: F401
from aimdk_msgs.msg._qr_code import QRCode  # noqa: F401
from aimdk_msgs.msg._qr_point import QRPoint  # noqa: F401
from aimdk_msgs.msg._region import Region  # noqa: F401
from aimdk_msgs.msg._request_header import RequestHeader  # noqa: F401
from aimdk_msgs.msg._response_header import ResponseHeader  # noqa: F401
from aimdk_msgs.msg._robot_resource import RobotResource  # noqa: F401
from aimdk_msgs.msg._robot_resource_mapping import RobotResourceMapping  # noqa: F401
from aimdk_msgs.msg._slave_device import SlaveDevice  # noqa: F401
from aimdk_msgs.msg._system_status import SystemStatus  # noqa: F401
from aimdk_msgs.msg._touch_state import TouchState  # noqa: F401
from aimdk_msgs.msg._tts_priority_level import TtsPriorityLevel  # noqa: F401
