from aimdk_msgs.srv._abandon_audio_focus import AbandonAudioFocus  # noqa: F401
from aimdk_msgs.srv._execute_action_resource import ExecuteActionResource  # noqa: F401
from aimdk_msgs.srv._get_all_joint_state import GetAllJointState  # noqa: F401
from aimdk_msgs.srv._get_current_input_source import GetCurrentInputSource  # noqa: F401
from aimdk_msgs.srv._get_hand_type import GetHandType  # noqa: F401
from aimdk_msgs.srv._get_mc_action import GetMcAction  # noqa: F401
from aimdk_msgs.srv._get_mic_source_request import GetMicSourceRequest  # noqa: F401
from aimdk_msgs.srv._get_mute import GetMute  # noqa: F401
from aimdk_msgs.srv._get_robot_resources import GetRobotResources  # noqa: F401
from aimdk_msgs.srv._get_stored_map_by_name import GetStoredMapByName  # noqa: F401
from aimdk_msgs.srv._get_system_state import GetSystemState  # noqa: F401
from aimdk_msgs.srv._get_volume import GetVolume  # noqa: F401
from aimdk_msgs.srv._migrate_system_state import MigrateSystemState  # noqa: F401
from aimdk_msgs.srv._play_audio_file import PlayAudioFile  # noqa: F401
from aimdk_msgs.srv._play_emoji import PlayEmoji  # noqa: F401
from aimdk_msgs.srv._play_media_file import PlayMediaFile  # noqa: F401
from aimdk_msgs.srv._play_tts import PlayTts  # noqa: F401
from aimdk_msgs.srv._play_video import PlayVideo  # noqa: F401
from aimdk_msgs.srv._play_video_group import PlayVideoGroup  # noqa: F401
from aimdk_msgs.srv._request_audio_focus import RequestAudioFocus  # noqa: F401
from aimdk_msgs.srv._set_agent_properties_request import SetAgentPropertiesRequest  # noqa: F401
from aimdk_msgs.srv._set_mc_action import SetMcAction  # noqa: F401
from aimdk_msgs.srv._set_mc_input_source import SetMcInputSource  # noqa: F401
from aimdk_msgs.srv._set_mc_preset_motion import SetMcPresetMotion  # noqa: F401
from aimdk_msgs.srv._set_mic_source_request import SetMicSourceRequest  # noqa: F401
from aimdk_msgs.srv._set_mute import SetMute  # noqa: F401
from aimdk_msgs.srv._set_pmu_led import SetPmuLed  # noqa: F401
from aimdk_msgs.srv._set_volume import SetVolume  # noqa: F401
