# --------------------------------------------------------------------------------------------------------------
# 播放机器人上灵创动作
# --------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# 请求头
CommonRequest header

string resource_key

string resource_version

SlaveDevice[] slaves

# 直接使用json
string meta

# ---------------------------------------------------- req
---
# ---------------------------------------------------- resp

# ----------------------------------------------------
# 响应头
CommonResponse header