# --------------------------------------------------------------------------------------------------------------
# 获取机器人上资源的服务
# --------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------
# 请求头
CommonRequest header

# ---------------------------------------------------- req
---
# ---------------------------------------------------- resp

# ----------------------------------------------------
# 响应头
CommonResponse header

# ----------------------------------------------------
# 机上资源信息
RobotResource[] robot_resources